/*
 * ADHOC 47 MORTAR REGIMENT — DASHBOARD ACCESS SETTINGS
 * -----------------------------------------------------------------------
 * This file controls who can switch the dashboard into Edit Mode.
 *
 * DEFAULT LOGIN (change this before real use):
 *     Username: admin
 *     Password: mortar47
 *
 * TO CHANGE THE PASSWORD:
 *   1. Open "set-password.html" (in this same folder) in any browser.
 *   2. Type the username and password you want.
 *   3. Copy the line it gives you and paste it over ADMIN_HASH below.
 *   4. Save this file and re-upload/redeploy.
 *
 * ---------------------------------------------------------------------
 * IMPORTANT — HOW STRONG IS THIS?
 *
 * This dashboard is a set of plain files with no server behind it, so the
 * check below happens inside the viewer's own browser. The password itself
 * is NOT stored here (only a one-way hash of it), but a determined person
 * who opens the page source can still bypass the prompt entirely.
 *
 * Treat this as a "keep honest people out" lock, like a sign on a door —
 * NOT as real security. Anything genuinely sensitive should not be put on
 * a page that untrusted people can open. Control who can reach the URL.
 * ---------------------------------------------------------------------
 */

window.DASHBOARD_CONFIG = {
  // Username is checked case-insensitively.
  ADMIN_USER: "admin",

  // SHA-256 of "username:password" — generated by set-password.html.
  // Current value corresponds to  admin / mortar47
  ADMIN_HASH: "312fe1c95d94dec19bc9deb3ba1a07c7ef97ac15ead6580e8cb3efb71144e226",

  // Set to false to drop the login entirely and let anyone with the link
  // edit (access then depends purely on who can reach the page).
  REQUIRE_LOGIN: true
};
